//SSl Certificate path
// ignore_for_file: non_constant_identifier_names, file_names

String certificate = "assets/certificate/tnrd_tn_gov_in.pem";

//png icons
String splash = "assets/images/tax.png";
String lock = "assets/images/lock.png";
String tamilnadu_logo = "assets/images/tamilnadu_logo.png";
String user = "assets/images/user.png";
String warnings = "assets/images/warning.png";
String logo = "assets/images/logo.png";
String login = "assets/images/login.png";
String logout = "assets/images/log_out.png";
String property = "assets/images/property.png";
String loginEnc = "assets/images/login_enc.jpg";
String loginPass = "assets/images/login_pass.jpg";
String house = "assets/images/house.png";
String water = "assets/images/water.png";
String professional = "assets/images/professional.png";
String professional1 = "assets/images/professional1.png";
String nontax = "assets/images/non_tax.png";
String nontax1 = "assets/images/nontax1.png";
String trade = "assets/images/trade.png";
String house_tax = "assets/images/house_tax.png";
String download = "assets/images/downloading.png";
String quick_pay = "assets/images/quick_pay.png";
String quick_pay1 = "assets/images/quick_pay1.png";
String download_receipt = "assets/images/download_receipt.png";
String due4 = "assets/images/due4.png";
String reciept = "assets/images/reciept.png";
String bg = "assets/images/bg.png";
String bg1 = "assets/images/bg1.png";
String right_arrow = "assets/images/right_arrow.png";
String left_arrow = "assets/images/leftt_arrow.png";
String right_arrow_icon = "assets/images/right_arrow_icon.png";
String village = "assets/images/village.png";
String village_development = "assets/images/village_2.png";
String check_transaction_status = "assets/images/invoice.png";
String group = "assets/images/group.png";
String utils = "assets/images/utility.png";
String payment_gateway = "assets/images/payment_gateway.png";
String tick = "assets/images/tick.png";
String unchecked = "assets/images/unchecked.png";
String waitingImg = "assets/images/waiting.png";
String download_img = "assets/images/download_2.png";
String rightarrow = "assets/images/rightarrow.png";
String downarrow = "assets/images/downarrow.png";
String waiting1 = "assets/images/waiting1.png";
String tax_public_icon = "assets/images/tax_public_icon.png";
String tax_img = "assets/images/tax_img.png";
String tax_logo = "assets/images/tax_logo.png";
String transaction_history = "assets/images/transaction_history.png";
String submit = "assets/images/submit.png";
String all = "assets/images/all.png";
String search = "assets/images/search.png";
String search1 = "assets/images/search1.png";
String warning_png = "assets/images/warning.png";
String delete_png = "assets/images/delete.png";
String location = "assets/images/location.png";
String datepicker_icon = "assets/images/datepicker_icon.png";
String history = "assets/images/history.png";
String currency = "assets/images/currency.png";
String add_user = "assets/images/add_user.png";
String download_ic = "assets/images/download.png";
String currency_ic = "assets/images/currency_ic.png";
String vptax = "assets/images/vptax.png";
String vptax1 = "assets/images/vptax1.png";
String tap = "assets/images/tap.png";
String lock_ic = "assets/images/lock_ic.png";
String taxes = "assets/images/taxes.png";
String taxs_image = "assets/images/taxs_image.png";
String loader_1 = 'assets/images/loader_1.png';
String loader_2 = 'assets/images/loader_2.png';

String help = 'assets/images/help.svg';
String failure = 'assets/images/failure.svg';
String success = 'assets/images/success.svg';
String warning = 'assets/images/warning.svg';

String back = 'assets/images/back.svg';
String bubbles = 'assets/images/bubbles.svg';

String spinner = 'assets/images/spinner.gif';
String spinner1 = 'assets/images/spinner1.gif';
String loader = 'assets/images/loader.png';
